#!/bin/bash

# Function to kill ng-build then exit the script
function ctrl_c {
    echo "\n\nexiting...\n"
    kill ${pid}
    exit 0
}

base_dir=`pwd`

# remove dist and start the build in parallel
rm -Rf "${base_dir}/dist"
ng build --sm=true --base-href "${base_dir}/dist/" -w &
pid=$!
trap "ctrl_c" INT

# Wait for dist folder to be created by build
while [ ! -d "${base_dir}/dist" ]; do
    sleep .5s
done
sleep .5s
echo "\n'${base_dir}/dist' found, starting electron app...\n"

electron -i . debug-mode

ctrl_c